[package]
name = "fluence-fvm-sdk"
description = "Fluence SDK for a FVM actor which provides RandomX syscall"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
repository = "https://github.com/filecoin-project/ref-fvm"

[lib]
crate-type = ["lib"]

[dependencies]
fvm_shared = { version = "3.2.0", path = "../../ref-fvm/shared" }
## num-traits; disabling default features makes it play nice with no_std.
num-traits = { version = "0.2.14", default-features = false }
