[package]
name = "fluence-fendermint-syscall"
description = "Implementation of RandomX syscall for Fendermint"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2021"
publish = true

[dependencies]
fvm = "4.1.0"
fvm_shared = "4.1.0"
randomx-rs = "1.3.0"
